spring:
  datasource:
    url: "jdbc:postgresql://101.133.231.235:15432/study?\
          ssl=true&\
          sslmode=verify-ca&\
          sslrootcert=D:/Workspace/config/postgresql/root-ca.crt&\
          sslkey=D:/Workspace/config/postgresql/client.key.pk8&\
          sslcert=D:/Workspace/config/postgresql/client.crt"
    username: chen
  data:
    redis:
      host: localhost
      port: 6379
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/59b48c05-1e21-49cb-9650-60199b178ae8/v2.0

        registration:
          azure-dev:
            provider: azure
            client-id: 72c3ed3d-ba03-42ab-81e4-4ff7fba718ce
            client-secret: YoU8Q~A.KRZ1xD1pohKKyNsBqOulIM2OT.1t9cZ7
            redirect-uri: http://localhost:8080/login/oauth2Callback
            scope:
              - api://72c3ed3d-ba03-42ab-81e4-4ff7fba718ce/loginInfo
default-prefix: cache
default-expire: 14400s
default-time-zone: Asia/Shanghai

logging:
  level:
    xyz.xyz.chen.member.repository: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true



config:
  default-system-id: 10000
  default-system-name: system
