name: create release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:
    env: 
      is_release: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.output.outputs.ver }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('./pom.xml') }}-${{ hashFiles('./library-management-app/pom.xml') }}
          restore-keys: maven-${{ hashFiles('./pom.xml') }}-${{ hashFiles('./library-management-app/pom.xml') }}
      - id: get-version
        uses: jactions/maven-version@v1.2.0
        with:
          pom: ./library-management-app/pom.xml

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Check TAG
        run: echo "ver=${{ steps.get-version.outputs.version }}.${{ steps.commit.outputs.short }}" >> $GITHUB_ENV

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        
      - name: Build JAR
        run: mvn  -B clean package -Dmaven.test.skip=true

      - name: Rename JAR
        run: mv ./library-management-app/target/*.jar ./lma.$(date +%Y-%m-%d).${{ steps.previoustag.outputs.tag }}.${{ steps.commit.outputs.short }}.jar

      - name: Create changelog text
        id: changelog
        if: ${{ env.is_release }}
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/tag-changelog-config.js

      - name: Check CHANGELOG
        if: ${{ env.is_release }}
        run: echo "${{ steps.changelog.outputs.changes }}" >> change.md

      - name: Release
        if: ${{ env.is_release }}
        uses: softprops/action-gh-release@v1
        with:
          body_path: change.md
          prerelease: false
          files: ./*.jar