name: pull request check (web)

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened ]
    paths:
      - 'web-apps/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          ache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm -r build