name: pull request check

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened ]
    paths:
      - 'backend/**'
    
env:
  PARENT_PATH: './backend'
  LMA_PATH: './backend/lma'
  PARENT_POM: './backend/parent/pom.xml'
  LMA_POM: './backend/lma/pom.xml'    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.output.outputs.ver }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Build JAR
        run: mvn -f ${{env.PARENT_POM}}  -B clean package -Dmaven.test.skip=true

      - name: Rename JAR
        run: mv ${{env.LMA_PATH}}/target/*.jar ./app.$(date +%Y-%m-%d).${{ steps.commit.outputs.short }}.jar